-----------------------------------------------------------------------------------------------------------------------
/*declare @fch_inicio datetime = '2020-27-04 00:00:00'
declare @fch_fin    datetime = '2020-27-04 23:59:59'
declare @contrato    char(10) = 'EPS017'
declare @centro     char(20) = '02'*/
-----------------------------------------------------------------------------------------------------------------------
WITH priest (ingreso, estancia)
	AS
	(
		select est.adningres, min(est.oid)
		from dgempres21..adningreso ing inner join dgempres21..hpnestanc est on  est.adningres=ing.oid
		inner join dgempres21..slnfactur fac on fac.ADNINGRESO=ing.OID 
		INNER JOIN DgEmpres21..GENDETCON det ON fac.GENDETCON=det.OID
		where ing.AINESTADO <> (2)
		AND fac.SFAFECFAC >= '2020-27-02 00:00:00'
	    AND fac.SFAFECFAC <= '2020-27-03 23:59:59'
		AND det.GDECODIGO = 'EPS01701'
		/*AND fac.SFAFECFAC >= @fch_inicio
	    AND fac.SFAFECFAC <= @fch_fin
		AND det.GDECODIGO = @contrato*/
		group by est.adningres
	)
-----------------------------------------------------------------------------------------------------------------------
SELECT SLNFACTUR.SFANUMFAC AS NUM_FACTURA, CONVERT(VARCHAR,SLNFACTUR.SFAFECFAC) AS FECHA_FACTURA
	,CONVERT(VARCHAR,SLNFACTUR.SFATOTFAC) AS TOTAL_FACTURA
	,CONVERT(VARCHAR,SLNFACTUR.SFAVARERE) AS VALOR_RETENCION
	,CONVERT(VARCHAR,SLNFACTUR.SFAVALPAC) AS VALOR_PACIENTE
	,ADNINGRESO.AINNUMAUT AS NO_AUTORIZACION
	,ADNINGRESO.AINCONSEC AS NO_INGRESO
	,ADNINGRESO.AINFECING AS FECHA_INGRESO
	,ADNEGRESO.ADEFECSAL AS FECHA_EGRESO
	,ADNEGRESO.OID AS NO_EGRESO
	,ADNINGRESO.AINFECHOS AS FECHA_HOSPITALIZACION
	,CASE GENPACIEN.PACTIPDOC WHEN 0 THEN '' WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN 8 THEN '' WHEN 9 THEN 'SC' WHEN 10 THEN 'NV' WHEN 11 THEN 'CD' WHEN 12 THEN 'PE' END AS TIPO_IDENTIFICACION 
	,GENPACIEN.PACNUMDOC AS IDENTIFICACION
	,GENPACIEN.GPANOMCOM AS PACIENTE
	,GENDETCON.GDECODIGO AS COD_PLAN 
	,GENDETCON.GDENOMBRE AS PLAN_BENEFICIO 
	,CASE ADNINGRESO.ainurgcon WHEN 0 THEN 'URGENCIAS' WHEN 1 THEN 'CONSULTA EXTERNA' WHEN 2 THEN 'NACIDO' WHEN 3 THEN 'REMITIDO' WHEN 4 THEN 'HOSPITALIZACION URGENCIAS' WHEN 5 THEN 'HOSPITALIZACION' WHEN 6 THEN 'IMAGENES' WHEN 7 THEN 'LABORATORIO' ELSE 'OTRO' END AS INGRESO_POR 
	,CASE ADNINGRESO.AINTIPING WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END AS TIPO_INGRESO 
	,GENUSUARIO1.USUDESCRI AS USUARIO_FACTURA, HPNDEFCAM.HCACODIGO AS CAMA
	,ROUND(CONVERT(INT, GETDATE()) - CONVERT(INT, ADNINGRESO.ainfechos), 1) AS dias_U_C
	,ROUND(CONVERT(INT, GETDATE()) - CONVERT(INT, e1.hesfecing), 1) AS dias_T
	,ROUND((CONVERT (INT, GETDATE()) - CONVERT(INT, GENPACIEN.gpafecnac)) / 365, 0) as edad
FROM DgEmpres21..SLNFACTUR INNER JOIN DgEmpres21..ADNINGRESO ON SLNFACTUR.ADNINGRESO = ADNINGRESO.OID 
	INNER JOIN DgEmpres21..GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN 
	INNER JOIN DgEmpres21..GENDETCON ON GENDETCON.OID = SLNFACTUR.GENDETCON 
	INNER JOIN DgEmpres21..GENTERCER ON GENTERCER.OID = GENDETCON.GENTERCER1 
	INNER JOIN DgEmpres21..GENUSUARIO AS GENUSUARIO1 ON GENUSUARIO1.OID = SLNFACTUR.GENUSUARIO1 
	INNER JOIN DgEmpres21..GENMUNICI ON GENMUNICI.OID = GENPACIEN.DGNMUNICIPIO 
	INNER JOIN DgEmpres21..GENDEPTO ON GENDEPTO.OID = GENMUNICI.GENDEPTO 
	LEFT JOIN DgEmpres21..HPNDEFCAM  ON ADNINGRESO.HPNDEFCAM=HPNDEFCAM.OID
	LEFT JOIN DgEmpres21..ADNEGRESO ON ADNEGRESO.ADNINGRESO = ADNINGRESO.OID
	LEFT JOIN priest pri ON pri.ingreso=ADNINGRESO.oid
	LEFT JOIN DgEmpres21..HPNESTANC e1 ON pri.estancia=e1.oid
WHERE SLNFACTUR.SFAFECFAC >= '2020-27-02 00:00:00'
	AND SLNFACTUR.SFAFECFAC <= '2020-27-03 23:59:59'
	AND GENDETCON.GDECODIGO = 'EPS01701'
	AND ADNINGRESO.AINESTADO <> 2  
	AND SLNFACTUR.SFADOCANU = 0
/*SLNFACTUR.SFAFECFAC >= @fch_inicio
	AND SLNFACTUR.SFAFECFAC <= @fch_fin
    AND GENDETCON.GDECODIGO = @contrato
	AND ADNINGRESO.AINESTADO <> 2  
	AND SLNFACTUR.SFADOCANU = 0*/
ORDER BY 
	SLNFACTUR.SFANUMFAC 
-----------------------------------------------------------------------------------------------------------------------
--select top 5 * from GENPACIEN where PACNUMDOC='86084927'
--select top 5 * from ADNEGRESO order by oid DESC
--select top 5 * from GENDETCON order by oid DESC
--select top 5 HPNDEFCAM, * from ADNINGRESO where AINTIPING=2 order by oid DESC
--select top 5 * from HPNDEFCAM order by oid DESC
-----------------------------------------------------------------------------------------------------------------------