select CAM.HCACODIGO CAMA, SUB.HSUCODIGO SUB_Grupo, PAC.PACNUMDOC IDENTIFICACIÓN, PAC.GPANOMCOM PACIENTE, ING.AINCONSEC INGRESO
, MED.GMECODIGO ENFERMERA_SOLICITA, CAB.HCSFECHA FECHA_SOLICITUD, DET.HCSCANTID CANTIDAD_Solicitada, PRO.IPRCODIGO CODIGO, PRO.IPRDESCOR PRODUCTO
, MEDa.GMECODIGO ENFERMERA_REGISTRA, CON.HCRHORREG FECHA_REGISTRO, CONd.HCNCANT CANTIDAD_Registrada 
from DGEMPRES01..HCNREGENF REG Inner Join DGEMPRES01..genpacien PAC  ON REG.genpacien=PAC.OID
Inner Join DGEMPRES01..ADNINGRESO ING ON REG.ADNINGRESO = ING.OID And REG.genpacien=ING.genpacien and ING.genpacien=PAC.OID
Inner Join DGEMPRES01..HCNSOLMED CAB  ON CAB.HCNREGENF=REG.OID
Inner Join DGEMPRES01..HCNSOLMEDD DET ON DET.HCNSOLMED=CAB.OID
Inner Join DGEMPRES01..GENMEDICO MED  ON CAB.GENMEDICO=MED.OID
Inner Join DGEMPRES01..INNPRODUC PRO  ON DET.INNPRODUC=PRO.OID
Inner Join DGEMPRES01..HPNDEFCAM CAM  ON ING.hpndefcam = CAM.oid 
Inner Join DGEMPRES01..HPNSUBGRU SUB  ON CAM.HPNSUBGRU = SUB.OID
Inner Join DGEMPRES01..HCNCONSUM CON  ON CON.HCNREGENF=REG.OID AND CON.HCNSOLMEDD=DET.OID
Inner Join DGEMPRES01..HCNCONSUMSUM CONd ON CONd.HCNCONSUM=CON.OID
Inner Join DGEMPRES01..GENMEDICO MEDa ON CON.GENMEDICO=MEDa.OID
where ING.AINESTADO = 0 
order by CAM.HCACODIGO, ING.AINCONSEC, CAB.OID