------------------------------------------------------------------------------------------------------------------------------------------
declare @fch_inicio   datetime = '2020-01-12 00:00:00'
declare @fch_fin      datetime = '2020-02-12 23:59:59'
declare @especialidad char(20) = ''--Var19
declare @centro       char(20) = '2'--Var28
declare @medico       char(20) = ''--Var54
declare @usuario      char(20) = ''--Var67
declare @contrato      char(20) = ''--Var2
------------------------------------------------------------------------------------------------------------------------------------------
SELECT pac.PACNUMDOC ident_pac, cit.CCMPACDOC ident_cit, cit.CCMPACNOM nom_pac_cit
	,RTRIM(LTRIM(pac.GPANOMCOM)) nom_pac
	,esp.geedescri especialidad, med.GMECODIGO medico, cen.ACACODIGO cod_cen, cit.CCMFECASI Fec_Asig, cit.CCMFECCIT Fec_Cita, cit.CCMFECPAC Fec_Req_Paciente
	,DATEDIFF(HOUR,cit.CCMFECASI,cit.CCMFECCIT) Tiempo_horas, DATEDIFF(DAY,cit.CCMFECASI,cit.CCMFECCIT) Tiempo_dias 
	
	,CASE(cit.CCMESTADO) WHEN 0 THEN 'Asig' WHEN 1 THEN 'Canc' WHEN 2 THEN 'Cump' WHEN 3 THEN 'Incu'
		WHEN 4 THEN 'Factu' ELSE 'Otro' END Estado
	
	,CASE WHEN cit.CCMESTADO = 2 OR cit.CCMESTADO = 4 THEN COALESCE(HCNFOLIO.ADNINGRESO, ADNINGRESO.ADNINGRESO) ELSE NULL END AS oid_ingreso	
	,CASE WHEN cit.CCMESTADO = 2 OR cit.CCMESTADO = 4 THEN COALESCE(HCNFOLIO.HCFECFOLI, ADNINGRESO.HCFECFOLI) ELSE NULL END AS Fec_Atencion
	,CASE WHEN cit.CCMESTADO = 2 OR cit.CCMESTADO = 4 THEN DATEDIFF(MINUTE, cit.CCMFECCIT, COALESCE(HCNFOLIO.HCFECFOLI, ADNINGRESO.HCFECFOLI)) ELSE NULL END AS Tiempo_Atencion_Min
	,CASE WHEN cit.CCMESTADO = 2 OR cit.CCMESTADO = 4 THEN DATEDIFF(HOUR, cit.CCMFECCIT, COALESCE(HCNFOLIO.HCFECFOLI, ADNINGRESO.HCFECFOLI)) ELSE NULL END AS Tiempo_Atencion_Hor
	
	,usu.USUNOMBRE usuario
	
	,CASE(cit.ccmtipasi) WHEN 0 THEN 'Pers' WHEN 1 THEN 'Tele' WHEN 2 THEN 'Urge' WHEN 3 THEN 'Avan'
		WHEN 4 THEN 'Inter' ELSE 'Otro' END Tip_Asig
	,CASE(cit.CCMESTCIT) WHEN 0 THEN 'Priv' WHEN 1 THEN 'Cont' WHEN 2 THEN 'Remi' 
		WHEN 3 THEN 'Espe' ELSE 'Otro' END Estilo
	,cit.CCMOBSERV observacion
	,act.CMACODIGO cod_actividad
	,act.CMANOMBRE actividad 
	
	,COALESCE(HCNFOLIO.GECCODIGO, ADNINGRESO.GECCODIGO, GENCONTRA.GECCODIGO, GENCONTRA2.GECCODIGO) cod_entidad
	,COALESCE(HCNFOLIO.GECNOMENT, ADNINGRESO.GECNOMENT, GENCONTRA.GECNOMENT, GENCONTRA2.GECNOMENT) entidad
FROM DGEMPRES01..CMNCITMED cit INNER JOIN DGEMPRES01..GENESPECI esp  ON cit.GENESPECI=esp.OID
	INNER JOIN DGEMPRES01..GENUSUARIO usu ON cit.GENUSUARIO1=usu.OID
	INNER JOIN DGEMPRES01..GENMEDICO med  ON cit.GENMEDICO1=med.OID
	INNER JOIN DGEMPRES01..CMNHORMED hor  ON cit.CMNHORMED=hor.OID
	INNER JOIN DGEMPRES01..ADNCENATE cen  ON hor.ADNCENATE=cen.OID
	INNER JOIN DGEMPRES01..CMNTIPACT act  ON act.OID = cit.CMNTIPACT
	LEFT JOIN DGEMPRES01..GENPACIEN pac   ON cit.CCMPACDOC=pac.PACNUMDOC 
	LEFT JOIN DGEMPRES01..GENDETCON ON cit.GENDETCON = GENDETCON.OID
	LEFT JOIN DGEMPRES01..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID 
	LEFT JOIN DGEMPRES01..GENDETCON GENDETCON2 ON pac.GENDETCON = GENDETCON2.OID
	LEFT JOIN DGEMPRES01..GENCONTRA GENCONTRA2 ON GENDETCON2.GENCONTRA1 = GENCONTRA2.OID 
	
	OUTER APPLY (
		SELECT TOP 1
			HCNFOLIO.ADNINGRESO
			,ADNINGRESO.GENDETCON
			,GENDETCON.GDECODIGO
			,GENDETCON.GDENOMBRE
			,GENCONTRA.GECCODIGO
			,GENCONTRA.GECNOMENT
			,HCNFOLIO.HCFECFOLI
		FROM 
			DGEMPRES01..HCNFOLIO 
			INNER JOIN DGEMPRES01..ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
			INNER JOIN DGEMPRES01..GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
			INNER JOIN DGEMPRES01..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID
		WHERE
			HCNFOLIO.CMNCITMED = cit.OID 
		ORDER BY 
			HCNFOLIO.OID ASC
		) HCNFOLIO 
	
	OUTER APPLY (
		SELECT TOP 1 
			ADNINGRESO.OID AS ADNINGRESO
			,ADNINGRESO.GENDETCON
			,GENDETCON.GDECODIGO
			,GENDETCON.GDENOMBRE
			,GENCONTRA.GECCODIGO
			,GENCONTRA.GECNOMENT
			,COALESCE(FOLIO2.HCFECFOLI, ADNINGRESO.AINFECING) HCFECFOLI
		FROM 
			DGEMPRES01..ADNINGRESO 
			INNER JOIN DGEMPRES01..GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
			INNER JOIN DGEMPRES01..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID
			OUTER APPLY (
				SELECT TOP 1
					HCNFOLIO2.HCFECFOLI
				FROM 
					DGEMPRES01..HCNFOLIO HCNFOLIO2
				WHERE
					HCNFOLIO2.ADNINGRESO = ADNINGRESO.OID
				ORDER BY 
					HCNFOLIO2.OID ASC
			) AS FOLIO2
		WHERE 
			ADNINGRESO.GENPACIEN = cit.GENPACIEN
			AND YEAR(ADNINGRESO.AINFECING) = YEAR(cit.CCMFECCIT)
			AND MONTH(ADNINGRESO.AINFECING) = MONTH(cit.CCMFECCIT)
			AND DAY(ADNINGRESO.AINFECING) = DAY(cit.CCMFECCIT) 
			--AND ADNINGRESO.AINURGCON <> 0
		ORDER BY 
			ADNINGRESO.AINURGCON DESC
	) ADNINGRESO 
	
WHERE 
	cit.CCMFECASI >= @fch_inicio
	AND cit.CCMFECASI <= @fch_fin
	AND (esp.GEECODIGO = @especialidad OR @especialidad='')
	AND (cen.ACACODIGO = @centro OR @centro='')
	AND (med.GMECODIGO = @medico OR @medico='')
	AND (usu.USUNOMBRE = @usuario OR @usuario = '')
	AND (GENCONTRA2.GECCODIGO = @contrato OR @contrato = '')
ORDER BY 
	cit.CCMESTADO
	,cit.CCMFECCIT
	,act.CMACODIGO
------------------------------------------------------------------------------------------------------------------------------------------
select top 5 * from cdo02_21..rep_consulta
select * from cdo02_21..rep_consulta_parametro where consulta=58

begin tran xxx
delete cdo02_21..rep_consulta_parametro where consulta=58 and secuencia=8
commit tran xxx
------------------------------------------------------------------------------------------------------------------------------------------