IF @empresa = '01'
BEGIN

SELECT 
	pac.PACNUMDOC ident_pac
	,cit.CCMPACDOC ident_cit
	,cit.CCMPACNOM nom_pac_cit
	,RTRIM(pac.pacprinom)+' '+RTRIM(pac.pacsegnom)+' '+RTRIM(pac.pacpriape)+' '+RTRIM(pac.pacsegape) nom_pac
	,tel.PACTELEFONO Telefono
	,esp.geedescri especialidad
	,med.GMECODIGO medico
	,cen.ACACODIGO cod_cen
	,cit.CCMFECASI Fec_Asig
	,cit.CCMFECCIT Fec_Cita, usu.USUNOMBRE usuario
	,CASE(cit.CCMESTADO) WHEN 0 THEN 'Asig' WHEN 1 THEN 'Canc' WHEN 2 THEN 'Cump' WHEN 3 THEN 'Incu'
		WHEN 4 THEN 'Factu' ELSE 'Otro' END Estado
    ,HCNFOLIO.HCNUMFOL folio
	,CASE(cit.ccmtipasi) WHEN 0 THEN 'Pers' WHEN 1 THEN 'Tele' WHEN 2 THEN 'Urge' WHEN 3 THEN 'Avan'
        WHEN 4 THEN 'Inter' ELSE 'Otro' END Tip_Asig
	,CASE(cit.CCMESTCIT) WHEN 0 THEN 'Priv' WHEN 1 THEN 'Cont' WHEN 2 THEN 'Remi' 
                      WHEN 3 THEN 'Espe' ELSE 'Otro' END Estado
	,cit.CCMOBSERV observacion
	,CMNTIPACT.CMACODIGO cod_actividad
	,CMNTIPACT.CMANOMBRE actividad
	,CASE(cit.CCMTIPCIT) WHEN 0 THEN 'NORMAL' WHEN 1 THEN 'EXTRA' WHEN 2 THEN 'GRUPAL' ELSE '' END tipo_cita
	,COALESCE(HCNFOLIO.ADNINGRESO, ADNINGRESO.ADNINGRESO) oid_ingreso
	,COALESCE(HCNFOLIO.GECCODIGO, ADNINGRESO.GECCODIGO) cod_entidad
	,COALESCE(HCNFOLIO.GECNOMENT, ADNINGRESO.GECNOMENT) cod_entidad
FROM 
	DGEMPRES01..CMNCITMED cit 
	LEFT JOIN DGEMPRES01..CMNTIPACT ON CMNTIPACT.OID = cit.CMNTIPACT
	LEFT JOIN DGEMPRES01..GENPACIEN pac ON cit.CCMPACDOC=pac.PACNUMDOC
	INNER JOIN DGEMPRES01..GENPACIENT tel ON pac.GENPACIENT=tel.OID
	INNER JOIN DGEMPRES01..GENESPECI esp  ON cit.GENESPECI=esp.OID
	INNER JOIN DGEMPRES01..GENUSUARIO usu ON cit.GENUSUARIO1=usu.OID
	INNER JOIN DGEMPRES01..GENMEDICO med  ON cit.GENMEDICO1=med.OID
	INNER JOIN DGEMPRES01..CMNHORMED hor  ON cit.CMNHORMED=hor.OID
	INNER JOIN DGEMPRES01..ADNCENATE cen  ON hor.ADNCENATE=cen.OID
	OUTER APPLY (
		SELECT TOP 1
			HCNFOLIO.ADNINGRESO
			,HCNFOLIO.HCNUMFOL
			,ADNINGRESO.GENDETCON
			,GENDETCON.GDECODIGO
			,GENDETCON.GDENOMBRE
			,GENCONTRA.GECCODIGO
			,GENCONTRA.GECNOMENT
		FROM 
			DGEMPRES01..HCNFOLIO 
			INNER JOIN DGEMPRES01..ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
			INNER JOIN DGEMPRES01..GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
			INNER JOIN DGEMPRES01..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID
		WHERE
			HCNFOLIO.CMNCITMED = cit.OID 
		ORDER BY 
			HCNFOLIO.OID DESC
		) HCNFOLIO 
	OUTER APPLY (
		SELECT TOP 1 
			ADNINGRESO.OID AS ADNINGRESO
			,ADNINGRESO.GENDETCON
			,GENDETCON.GDECODIGO
			,GENDETCON.GDENOMBRE
			,GENCONTRA.GECCODIGO
			,GENCONTRA.GECNOMENT
		FROM 
			DGEMPRES01..ADNINGRESO 
			INNER JOIN DGEMPRES01..GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
			INNER JOIN DGEMPRES01..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID
		WHERE 
			ADNINGRESO.GENPACIEN = cit.GENPACIEN
			AND YEAR(ADNINGRESO.AINFECING) = YEAR(cit.CCMFECCIT)
			AND MONTH(ADNINGRESO.AINFECING) = MONTH(cit.CCMFECCIT)
			AND DAY(ADNINGRESO.AINFECING) = DAY(cit.CCMFECCIT)
		ORDER BY 
			ADNINGRESO.OID DESC
	) ADNINGRESO 
WHERE
    cit.CCMFECCIT >= @fch_inicio
	AND cit.CCMFECCIT <= @fch_fin
	AND (esp.GEECODIGO = @especialidad or @especialidad='')
	AND (cen.ACACODIGO = @centro or @centro='')
	AND (med.GMECODIGO = @medico or @medico='')
ORDER BY
	hor.OID
	,cit.CCMFECCIT

END 
ELSE
BEGIN

SELECT 
	pac.PACNUMDOC ident_pac
	,cit.CCMPACDOC ident_cit
	,cit.CCMPACNOM nom_pac_cit
	,RTRIM(pac.pacprinom)+' '+RTRIM(pac.pacsegnom)+' '+RTRIM(pac.pacpriape)+' '+RTRIM(pac.pacsegape) nom_pac
	,esp.geedescri especialidad
	,med.GMECODIGO medico
	,cen.ACACODIGO cod_cen
	,cit.CCMFECASI Fec_Asig
	,cit.CCMFECCIT Fec_Cita, usu.USUNOMBRE usuario
	,CASE(cit.CCMESTADO) WHEN 0 THEN 'Asig' WHEN 1 THEN 'Canc' WHEN 2 THEN 'Cump' WHEN 3 THEN 'Incu'
		WHEN 4 THEN 'Factu' ELSE 'Otro' END Estado
    ,HCNFOLIO.HCNUMFOL folio
	,CASE(cit.ccmtipasi) WHEN 0 THEN 'Pers' WHEN 1 THEN 'Tele' WHEN 2 THEN 'Urge' WHEN 3 THEN 'Avan'
        WHEN 4 THEN 'Inter' ELSE 'Otro' END Tip_Asig
	,CASE(cit.CCMESTCIT) WHEN 0 THEN 'Priv' WHEN 1 THEN 'Cont' WHEN 2 THEN 'Remi' 
                      WHEN 3 THEN 'Espe' ELSE 'Otro' END Estado
	,cit.CCMOBSERV observacion
	,CMNTIPACT.CMACODIGO cod_actividad
	,CMNTIPACT.CMANOMBRE actividad
	,CASE(cit.CCMTIPCIT) WHEN 0 THEN 'NORMAL' WHEN 1 THEN 'EXTRA' WHEN 2 THEN 'GRUPAL' ELSE '' END tipo_cita
	,COALESCE(HCNFOLIO.ADNINGRESO, ADNINGRESO.ADNINGRESO) oid_ingreso
	,COALESCE(HCNFOLIO.GECCODIGO, ADNINGRESO.GECCODIGO) cod_entidad
	,COALESCE(HCNFOLIO.GECNOMENT, ADNINGRESO.GECNOMENT) cod_entidad
FROM 
	dgempres21..CMNCITMED cit 
	LEFT JOIN DGEMPRES21..CMNTIPACT ON CMNTIPACT.OID = cit.CMNTIPACT
	LEFT JOIN dgempres21..GENPACIEN pac ON cit.CCMPACDOC=pac.PACNUMDOC
	INNER JOIN dgempres21..GENESPECI esp  ON cit.GENESPECI=esp.OID
	INNER JOIN dgempres21..GENUSUARIO usu ON cit.GENUSUARIO1=usu.OID
	INNER JOIN dgempres21..GENMEDICO med  ON cit.GENMEDICO1=med.OID
	INNER JOIN dgempres21..CMNHORMED hor  ON cit.CMNHORMED=hor.OID
	INNER JOIN dgempres21..ADNCENATE cen  ON hor.ADNCENATE=cen.OID
	OUTER APPLY (
		SELECT TOP 1
			HCNFOLIO.ADNINGRESO
			,HCNFOLIO.HCNUMFOL
			,ADNINGRESO.GENDETCON
			,GENDETCON.GDECODIGO
			,GENDETCON.GDENOMBRE
			,GENCONTRA.GECCODIGO
			,GENCONTRA.GECNOMENT
		FROM 
			DGEMPRES21..HCNFOLIO 
			INNER JOIN DGEMPRES21..ADNINGRESO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
			INNER JOIN DGEMPRES21..GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
			INNER JOIN DGEMPRES21..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID
		WHERE
			HCNFOLIO.CMNCITMED = cit.OID 
		ORDER BY 
			HCNFOLIO.OID DESC
		) HCNFOLIO 
	OUTER APPLY (
		SELECT TOP 1 
			ADNINGRESO.OID AS ADNINGRESO
			,ADNINGRESO.GENDETCON
			,GENDETCON.GDECODIGO
			,GENDETCON.GDENOMBRE
			,GENCONTRA.GECCODIGO
			,GENCONTRA.GECNOMENT
		FROM 
			DGEMPRES21..ADNINGRESO 
			INNER JOIN DGEMPRES21..GENDETCON ON ADNINGRESO.GENDETCON = GENDETCON.OID
			INNER JOIN DGEMPRES21..GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID
		WHERE 
			ADNINGRESO.GENPACIEN = cit.GENPACIEN
			AND YEAR(ADNINGRESO.AINFECING) = YEAR(cit.CCMFECCIT)
			AND MONTH(ADNINGRESO.AINFECING) = MONTH(cit.CCMFECCIT)
			AND DAY(ADNINGRESO.AINFECING) = DAY(cit.CCMFECCIT)
		ORDER BY 
			ADNINGRESO.OID DESC
	) ADNINGRESO 
WHERE
    cit.CCMFECCIT >= @fch_inicio
	AND cit.CCMFECCIT <= @fch_fin
	AND (esp.GEECODIGO = @especialidad or @especialidad='')
	AND (cen.ACACODIGO = @centro or @centro='')
	AND (med.GMECODIGO = @medico or @medico='')
ORDER BY
	hor.OID
	,cit.CCMFECCIT

END