use DGEMPRES22
select top 5 * from HCNTRIAGE order by oid desc

select N0."OID", N0."ADNINGRESO", N5."HCENTRIAGE", N0."HCTCONFIR", N0."HCTNUMERO",N0."HCTFECTRI",N0."GPADOCUME",N0."GPAAPELLI",N0."GPASEGAPE",N0."GPANOMBRE",N0."GPASEGNOM",N0."HCTEDAD",N0."HCTUNEDAD",N0."HCTGENALERT",case when N0."GENMEDICO1" is null then 0 else N0."GENMEDICO1" end,case when N0."GEENENTADM" is null then 1 else 0 end,N0."GEENENTADM",N1."ENTCODIGO",N1."ENTNOMBRE",N0."DGESPECI",N2."GEECODIGO",N2."GEEDESCRI",case when N0."GENESPECIDES" is null then 1 else 0 end,N0."GENESPECIDES",N3."GEECODIGO",N3."GEEDESCRI",N0."ADNCENATE",N4."ACACODIGO",N4."ACANOMBRE",case when N0."ADNINGRESO" is null then 1 else 0 end,N0."ADNINGRESO",N5."AINCONSEC",N0."HCNCLAURGTR",N6."HCCODIGO",N6."HCDESCRIP",N6."HCCOLOR",N0."HCTPRMLLAM",N0."HCTHPRMLLAM",N0."HCTSGDLLAM",N0."HCTHSGDLLAM",N0."HCTTRCLLAM",N0."HCTHTCRLLAM",N0."HCTNOCONTS",N0."HCTCITAPRT" 
from (((((("dbo"."HCNTRIAGE" N0 left join "dbo"."GEENENTADM" N1 on (N0."GEENENTADM" = N1."OID"))
 left join "dbo"."GENESPECI" N2 on (N0."DGESPECI" = N2."OID"))
 left join "dbo"."GENESPECI" N3 on (N0."GENESPECIDES" = N3."OID"))
 left join "dbo"."ADNCENATE" N4 on (N0."ADNCENATE" = N4."OID"))
 left join "dbo"."ADNINGRESO" N5 on (N0."ADNINGRESO" = N5."OID"))
 left join "dbo"."HCNCLAURGTR" N6 on (N0."HCNCLAURGTR" = N6."OID"))
where (not ((N0."HCTCONFIR" = 1)) and (N0."HCTCITAPRT" is null or not ((N0."HCTCITAPRT" = 1))) 
and (N0."HCTNOCONTS" is null or not ((N0."HCTNOCONTS" = 1))))

--OID	HCTNUMERO
--713364	712389

select HCNCLAURGTR, * from HCNTRIAGE where HCNCLAURGTR IN (4, 5) and DATEDIFF(HH, HCFMODTRI, GETDATE()) > 0 and
(not ((HCTCONFIR = 1)) and (HCTCITAPRT is null or not ((HCTCITAPRT = 1))) and (HCTNOCONTS is null or not ((HCTNOCONTS = 1))))

select HCNCLAURGTR, * from HCNTRIAGE where OID in (713369, 713370, 713381)
select * from HCNCLAURGTR

update DGEMPRES22..HCNTRIAGE set HCTCONFIR=1, HCTRETVOLPAC=1, HCTHORETPAC=GETDATE()
, HCTCFECCONF=GETDATE(), HCTSALURGEN=1, HCTFECSALURG=GETDATE(), HCTOBSRETPAC='Clasificación 4 o 5, cierre automatico, remitir a la EPS'
where HCNCLAURGTR IN (4, 5) and DATEDIFF(hh, HCFMODTRI, GETDATE()) > 0 and
(not ((HCTCONFIR = 1)) and (HCTCITAPRT is null or not ((HCTCITAPRT = 1))) and (HCTNOCONTS is null or not ((HCTNOCONTS = 1))))

select top 5 ADNINGRESO, HCTCONFIR, * from DGEMPRES22..HCNTRIAGE where HCTNUMERO=719821
select top 5 HCENTRIAGE, * from DGEMPRES22..ADNINGRESO where OID=1905111