use DGEMPRES01
DBCC CHECKIDENT (CTNNIVEL, RESEED, 0);
DBCC CHECKIDENT (CTNCLASE, RESEED, 0);
DBCC CHECKIDENT (CTNCUENTA, RESEED, 0);
GO

select * from DGEMPRES01..CTNNIVEL
select * from DGEMPRES21..CTNNIVEL
select * from DGEMPRES01..CTNCLASE
select * from DGEMPRES21..CTNCLASE
select * from CTNCUENTA