SELECT * FROM DGEMPRES03..HCNTIPHIS A, 
DGEMPRES03..HCNDISHIS B, 
DGEMPRES01..HCNTIPHIS C, 
DGEMPRES01..HCNDISHIS D
WHERE A.OID = B.HCNTIPHIS AND C.OID = D.HCNTIPHIS AND A.HCCODIGO = 'C000P1' AND C.HCCODIGO = 'C000P1'

UPDATE D SET HCDLYTDIS = B.HCDLYTDIS,     
GEPREPMOD = B.GEPREPMOD,
HCNANCPER = B.HCNANCPER,
HCNANCDIS = B.HCNANCDIS,
HCNALTPER = B.HCNALTPER,
HCNALTDIS = B.HCNALTDIS 
FROM DGEMPRES03..HCNTIPHIS A,
DGEMPRES03..HCNDISHIS B,
DGEMPRES01..HCNTIPHIS C,
DGEMPRES01..HCNDISHIS D
WHERE A.OID = B.HCNTIPHIS AND C.OID = D.HCNTIPHIS AND A.HCCODIGO = 'C000P1' AND C.HCCODIGO = 'C000P1'

select top 5 * from dgempres03..HCNTIPHIS where HCCODIGO='C000P1'
select top 5 * from dgempres03..HCNDISHIS where HCNTIPHIS=34
select * from dgempres03..HCNCAMTHC where HCNTIPHIS=34

select top 5 * from dgempres02..HCNTIPHIS where HCCODIGO='C000P1'
select top 5 * from dgempres02..HCNDISHIS where HCNTIPHIS=34

select top 5 * from DGEMPRES01..HCNTIPHIS where HCCODIGO='C000P1'
select top 5 * from dgempres01..HCNDISHIS where HCNTIPHIS=34
select * from dgempres01..HCNCAMTHC where HCNTIPHIS=34
select * from dgempres03..HCNCAMTHC where HCNTIPHIS=34

select top 5 * from DGEMPRES01..HCNTIPHIS where HCCODIGO='C000P1'
select top 5 * from DGEMPRES03..HCNTIPHIS where HCCODIGO='C000P1'

begin tran xxx
--DBCC CHECKIDENT ('dgempres01..HCNTIPHIS', RESEED, 65);
--DBCC CHECKIDENT ('dgempres01..HCNDISHIS', RESEED, 65);
--DBCC CHECKIDENT ('dgempres01..HCNCAMTHC', RESEED, 3601);
--delete dgempres01..HCNCAMTHC where HCNTIPHIS=68
--update dgempres01..HCNDISHIS set HCNTIPHIS=33 where OID=34
--delete dgempres01..HCNDISHIS where OID=34
delete dgempres01..HCNTIPHIS where OID=68
commit tran xxx


select top 5 * from DGEMPRES01..HCNTIPHIS order by oid desc
select top 5 * from DGEMPRES01..HCNDISHIS order by oid desc
select top 5 * from dgempres01..HCNCAMTHC order by oid desc

begin tran xxx
/*insert into dgempres01..HCNDISHIS (HCNTIPHIS, HCNANCPER, HCNANCDIS, HCNALTPER, HCNALTDIS, HCDLYTDIS, GEPREPMOD, HCNMODHTM, OptimisticLockField, GEPREPMODXML, HCNEXPJS)
select NULL, HCNANCPER, HCNANCDIS, HCNALTPER, HCNALTDIS, HCDLYTDIS, GEPREPMOD, HCNMODHTM, OptimisticLockField, GEPREPMODXML, HCNEXPJS from dgempres03..HCNDISHIS where OID=34

insert into dgempres01..HCNTIPHIS (HCCODIGO, HCNOMBRE, GENESPECI, GENARESER, HCCAUEXT, HCFINCON, HCPERFOL, HCPERFOLAM, HCEXIDIA, HCEXINAM, HCEXINHO, HCODONTOHC, HCOBLIGA, HCBLOQUEA, HCEXCIMED, HCMAFOABR, HCPRVRFLAB, HCEXIPAQ, HCEXIPQE, HCEXISOC, HCEXIOBGR, HCEXIRVANTE, HCEXIDIETPAC, HCEXITRIAGE, HCCOPDIAGFO, HCCOPPLINFO, HCCOPPLEXFO, HCTHPYP, HCTHRESTVA, HCTHINASIS, HCTHEXHDINI, HCTHEXHDGRB, HCTHABESTPAC, HCTHFLDGURG, HCPRFOINCR, HCPRFOINFAC, HCFILING, HCFILINGPQ, HCTIPMODHC, HCENCRIP, HCNOTACLA, HCFOLRESINTER, HCFOLCONTREF, HCEXIANTE, HCTIPOSANTE, HCFLINAMBFAC, HCFLINHSPFAC, HCDIAFLAMBFA, HCDIAFLHSPFA, HCNMODWEB, HCOPCINI, HCEXIGES, HCEXIFECALTA, HCHCPREANEST, HCTIPCDASSD, HCEXGDAGING, HCEXGDAGIGR, HCHABDIEAMB, HCEXIVRACANTE, OptimisticLockField)
select HCCODIGO, HCNOMBRE, GENESPECI, GENARESER, HCCAUEXT, HCFINCON, HCPERFOL, HCPERFOLAM, HCEXIDIA, HCEXINAM, HCEXINHO, HCODONTOHC, HCOBLIGA, HCBLOQUEA, HCEXCIMED, HCMAFOABR, HCPRVRFLAB, HCEXIPAQ, HCEXIPQE, HCEXISOC, HCEXIOBGR, HCEXIRVANTE, HCEXIDIETPAC, HCEXITRIAGE, HCCOPDIAGFO, HCCOPPLINFO, HCCOPPLEXFO, HCTHPYP, HCTHRESTVA, HCTHINASIS, HCTHEXHDINI, HCTHEXHDGRB, HCTHABESTPAC, HCTHFLDGURG, HCPRFOINCR, HCPRFOINFAC, HCFILING, HCFILINGPQ, HCTIPMODHC, HCENCRIP, HCNOTACLA, HCFOLRESINTER, HCFOLCONTREF, HCEXIANTE, HCTIPOSANTE, HCFLINAMBFAC, HCFLINHSPFAC, HCDIAFLAMBFA, HCDIAFLHSPFA, HCNMODWEB, HCOPCINI, HCEXIGES, HCEXIFECALTA, HCHCPREANEST, HCTIPCDASSD, HCEXGDAGING, HCEXGDAGIGR, HCHABDIEAMB, HCEXIVRACANTE, OptimisticLockField from dgempres03..HCNTIPHIS where HCCODIGO='C000P1'

update DGEMPRES01..HCNTIPHIS set HCNDISHIS=66 where OID=66
update DGEMPRES01..HCNDISHIS set HCNTIPHIS=66 where OID=66
*/
insert into dgempres01..HCNCAMTHC (HCNTIPHIS, HCTIPCON, HCNOMBRE, HCDESCRIP, HCOBLIGA, HCRELEPIC, HCRELATIUR, HCRELAFURI, HCTITEPIC, HCRELCREF, HCTITCREF, HCEXPCON, HCEXPFOR, HCTDEXPR, HCEVAEXP, HCOBTHIS, HCOBTHISE, HCOBTHISEC, HCMODFOLA, HCNOGENSL, HCRELENFER, HCRELSIGVIT, HCRELCERTIF, HCPROPER, HCTITFOLIOSIUS, HCRELFOLIOSIUS, HCEPICSAL, HCRELGESRIES, HCRELAUTSER, HCTITAUTSER, HCRELRES2175, HCRELINDMED, HCRELEGRENAC, HCRELCDASO, HCRELCDAMN, HCRELINTCON, HCRELINTRES, OptimisticLockField, HCEXPFORWEB)
select 66, HCTIPCON, HCNOMBRE, HCDESCRIP, HCOBLIGA, HCRELEPIC, HCRELATIUR, HCRELAFURI, HCTITEPIC, HCRELCREF, HCTITCREF, HCEXPCON, HCEXPFOR, HCTDEXPR, HCEVAEXP, HCOBTHIS, HCOBTHISE, HCOBTHISEC, HCMODFOLA, HCNOGENSL, HCRELENFER, HCRELSIGVIT, HCRELCERTIF, HCPROPER, HCTITFOLIOSIUS, HCRELFOLIOSIUS, HCEPICSAL, HCRELGESRIES, HCRELAUTSER, HCTITAUTSER, HCRELRES2175, HCRELINDMED, HCRELEGRENAC, HCRELCDASO, HCRELCDAMN, HCRELINTCON, HCRELINTRES, OptimisticLockField, HCEXPFORWEB from dgempres03..HCNCAMTHC where HCNTIPHIS=34
commit tran xxx
