select * from DGEMPRES01..HCNTIPHIS where HCCODIGO='C00016'
select * from DGEMPRES03..HCNTIPHIS where HCCODIGO='C00016'

select * from DGEMPRES01..HCNDISHIS where HCNTIPHIS=68
select * from DGEMPRES03..HCNDISHIS where HCNTIPHIS=68

select * from DGEMPRES01..HCNDISHIS where HCNTIPHIS=68
select * from DGEMPRES03..HCNDISHIS where HCNTIPHIS=68

select top 5 * from DGEMPRES03..HCNTIPHIS order by OID desc
select top 5 * from DGEMPRES03..HCNDISHIS order by OID desc

update DGEMPRES03..HCNTIPHIS set OID=68 where HCCODIGO='C00016'
update DGEMPRES03..HCNDISHIS set OID=68 where HCNTIPHIS=68

select TOP 5 * from DGEMPRES01..HCNFOLIO where HCFECFOL > '20211201'
select TOP 5 * from DGEMPRES01..HCMC00016 ORDER BY OID DESC
select TOP 5 * from DGEMPRES03..HCMC00016 ORDER BY OID DESC

select LEN(HCCM09N44), LEN(HCCM01N45), LEN(HCCM03N46), LEN(HCCM03N47), LEN(HCCM03N48), * from DGEMPRES01..HCMP00001 
WHERE hcnfolio > 1096790 
order by 5 desc

select * from DGEMPRES01..HCNDISHIS where HCNTIPHIS=1
select * from DGEMPRES02..HCNDISHIS where HCNTIPHIS=1

select * from DGEMPRES01..HCNTIPHIS where HCCODIGO='C00MP1'
select * from DGEMPRES01..HCNDISHIS where HCNTIPHIS=68

select * from DGEMPRES01..HCNCAMTHC where HCNTIPHIS=1
select HCTIPCON, HCDESCRIP, * from DGEMPRES02..HCNCAMTHC where HCNTIPHIS=1 and OID > 3894


select * from DGEMPRES01..HCNCAMTHC where HCNTIPHIS=1

select top 5 * from DGEMPRES01..GENSERIPS where SIPCODIGO in ('906481','906801')
select top 5 * from DGEMPRES21..GENSERIPS where SIPCODIGO in ('906481','906801')

select top 5 * from DGEMPRES01..GENSERIPS where SIPCODIGO in ('906482')
select top 5 * from DGEMPRES21..GENSERIPS where SIPCODIGO in ('906482')

begin tran xxx
/*INSERT INTO DGEMPRES03..HCNTIPHIS --VALUES(HCCODIGO, HCNOMBRE, HCNDISHIS, GENESPECI, GENARESER, HCCAUEXT, HCFINCON, HCPERFOL, HCPERFOLAM, HCEXIDIA, HCEXINAM, HCEXINHO, HCODONTOHC, HCOBLIGA, HCBLOQUEA, HCEXCIMED, HCMAFOABR, HCPRVRFLAB, HCEXIPAQ, HCEXIPQE, HCEXISOC, HCEXIOBGR, HCEXIRVANTE, HCEXIDIETPAC, HCEXITRIAGE, HCCOPDIAGFO, HCCOPPLINFO, HCCOPPLEXFO, HCTHPYP, HCTHRESTVA, HCTHINASIS, HCTHEXHDINI, HCTHEXHDGRB, HCTHABESTPAC, HCTHFLDGURG, HCPRFOINCR, HCPRFOINFAC, HCFILING, HCFILINGPQ, HCTIPMODHC, HCENCRIP, HCNOTACLA, HCFOLRESINTER, HCFOLCONTREF, HCEXIANTE, HCTIPOSANTE, HCFLINAMBFAC, HCFLINHSPFAC, HCDIAFLAMBFA, HCDIAFLHSPFA, HCNMODWEB, HCOPCINI, HCEXIGES, HCEXIFECALTA, HCHCPREANEST, HCTIPCDASSD, HCEXGDAGING, HCEXGDAGIGR, HCHABDIEAMB, HCEXIVRACANTE, OptimisticLockField)
    SELECT HCCODIGO, HCNOMBRE, 67, GENESPECI, GENARESER, HCCAUEXT, HCFINCON, HCPERFOL, HCPERFOLAM, HCEXIDIA, HCEXINAM, HCEXINHO, HCODONTOHC, HCOBLIGA, HCBLOQUEA, HCEXCIMED, HCMAFOABR, HCPRVRFLAB, HCEXIPAQ, HCEXIPQE, HCEXISOC, HCEXIOBGR, HCEXIRVANTE, HCEXIDIETPAC, HCEXITRIAGE, HCCOPDIAGFO, HCCOPPLINFO, HCCOPPLEXFO, HCTHPYP, HCTHRESTVA, HCTHINASIS, HCTHEXHDINI, HCTHEXHDGRB, HCTHABESTPAC, HCTHFLDGURG, HCPRFOINCR, HCPRFOINFAC, HCFILING, HCFILINGPQ, HCTIPMODHC, HCENCRIP, HCNOTACLA, HCFOLRESINTER, HCFOLCONTREF, HCEXIANTE, HCTIPOSANTE, HCFLINAMBFAC, HCFLINHSPFAC, HCDIAFLAMBFA, HCDIAFLHSPFA, HCNMODWEB, HCOPCINI, HCEXIGES, HCEXIFECALTA, HCHCPREANEST, HCTIPCDASSD, HCEXGDAGING, HCEXGDAGIGR, HCHABDIEAMB, HCEXIVRACANTE, OptimisticLockField
    FROM DGEMPRES01..HCNTIPHIS WHERE OID = 68*/

/*INSERT INTO DGEMPRES03..HCNDISHIS --VALUES(HCNTIPHIS, HCNANCPER, HCNANCDIS, HCNALTPER, HCNALTDIS, HCDLYTDIS, GEPREPMOD, HCNMODHTM, OptimisticLockField, GEPREPMODXML, HCNEXPJS, HCNFORMCS, HCNFORMJS)
    SELECT HCNTIPHIS, HCNANCPER, HCNANCDIS, HCNALTPER, HCNALTDIS, HCDLYTDIS, GEPREPMOD, HCNMODHTM, OptimisticLockField, GEPREPMODXML, HCNEXPJS, HCNFORMCS, HCNFORMJS
    FROM DGEMPRES01..HCNDISHIS WHERE HCNTIPHIS = 68*/

UPDATE DGEMPRES03..HCNTIPHIS SET HCNDISHIS=68 WHERE OID=68

INSERT INTO DGEMPRES03..HCNCAMTHC --VALUES( HCNTIPHIS, HCTIPCON, HCNOMBRE, HCDESCRIP, HCOBLIGA, HCRELEPIC, HCRELATIUR, HCRELAFURI, HCTITEPIC, HCRELCREF, HCTITCREF, HCEXPCON, HCEXPFOR, HCTDEXPR, HCEVAEXP, HCOBTHIS, HCOBTHISE, HCOBTHISEC, HCMODFOLA, HCNOGENSL, HCRELENFER, HCRELSIGVIT, HCRELCERTIF, HCPROPER, HCTITFOLIOSIUS, HCRELFOLIOSIUS, HCEPICSAL, HCRELGESRIES, HCRELAUTSER, HCTITAUTSER, HCRELRES2175, HCRELINDMED, HCRELEGRENAC, HCRELCDASO, HCRELCDAMN, HCRELINTCON, HCRELINTRES, OptimisticLockField, HCEXPFORWEB)
    SELECT HCNTIPHIS, HCTIPCON, HCNOMBRE, HCDESCRIP, HCOBLIGA, HCRELEPIC, HCRELATIUR, HCRELAFURI, HCTITEPIC, HCRELCREF, HCTITCREF, HCEXPCON, HCEXPFOR, HCTDEXPR, HCEVAEXP, HCOBTHIS, HCOBTHISE, HCOBTHISEC, HCMODFOLA, HCNOGENSL, HCRELENFER, HCRELSIGVIT, HCRELCERTIF, HCPROPER, HCTITFOLIOSIUS, HCRELFOLIOSIUS, HCEPICSAL, HCRELGESRIES, HCRELAUTSER, HCTITAUTSER, HCRELRES2175, HCRELINDMED, HCRELEGRENAC, HCRELCDASO, HCRELCDAMN, HCRELINTCON, HCRELINTRES, OptimisticLockField, HCEXPFORWEB
    FROM DGEMPRES01..HCNCAMTHC WHERE HCNTIPHIS=68
rollback tran xxx
commit tran xxx

--1 Validar los cambios en el formato de la HC
ALTER TABLE DGEMPRES01..HCMP00001 ADD HCCM03N48 VARCHAR(20) NULL
--2 Actualizar los campos cifrados
--update DGEMPRES01..HCNDISHIS set HCNALTDIS=1020 where OID=1
update DGEMPRES03..HCNDISHIS set HCDLYTDIS=(select HCDLYTDIS from DGEMPRES01..HCNDISHIS where OID=68) where OID=68
update DGEMPRES03..HCNDISHIS set GEPREPMOD=(select GEPREPMOD from DGEMPRES01..HCNDISHIS where OID=68) where OID=68
update DGEMPRES03..HCNDISHIS set GEPREPMODXML=(select GEPREPMODXML from DGEMPRES01..HCNDISHIS where OID=68) where OID=68
--3 Actualizar los campos nuevos
INSERT INTO DGEMPRES01..HCNCAMTHC VALUES( HCNTIPHIS, HCTIPCON, HCNOMBRE, HCDESCRIP, HCOBLIGA, HCRELEPIC, HCRELATIUR, HCRELAFURI, HCTITEPIC, HCRELCREF, HCTITCREF, HCEXPCON, HCEXPFOR, HCTDEXPR, HCEVAEXP, HCOBTHIS, HCOBTHISE, HCOBTHISEC, HCMODFOLA, HCNOGENSL, HCRELENFER, HCRELSIGVIT, HCRELCERTIF, HCPROPER, HCTITFOLIOSIUS, HCRELFOLIOSIUS, HCEPICSAL, HCRELGESRIES, HCRELAUTSER, HCTITAUTSER, HCRELRES2175, HCRELINDMED, HCRELEGRENAC, HCRELCDASO, HCRELCDAMN, HCRELINTCON, HCRELINTRES, OptimisticLockField, HCEXPFORWEB)
    SELECT HCNTIPHIS, HCTIPCON, HCNOMBRE, HCDESCRIP, HCOBLIGA, HCRELEPIC, HCRELATIUR, HCRELAFURI, HCTITEPIC, HCRELCREF, HCTITCREF, HCEXPCON, HCEXPFOR, HCTDEXPR, HCEVAEXP, HCOBTHIS, HCOBTHISE, HCOBTHISEC, HCMODFOLA, HCNOGENSL, HCRELENFER, HCRELSIGVIT, HCRELCERTIF, HCPROPER, HCTITFOLIOSIUS, HCRELFOLIOSIUS, HCEPICSAL, HCRELGESRIES, HCRELAUTSER, HCTITAUTSER, HCRELRES2175, HCRELINDMED, HCRELEGRENAC, HCRELCDASO, HCRELCDAMN, HCRELINTCON, HCRELINTRES, OptimisticLockField, HCEXPFORWEB
    FROM DGEMPRES02..HCNCAMTHC WHERE HCNTIPHIS=1 and OID > 3894
commit tran xxx
rollback tran xxx

select top 1 * from DGEMPRES03..HCNTIPHIS order by OID desc
select top 1 * from DGEMPRES03..HCNDISHIS order by OID desc
select top 1 * from DGEMPRES03..HCNCAMTHC order by OID desc


begin tran xxx
DBCC CHECKIDENT ('DGEMPRES03..HCNTIPHIS', RESEED, 67);
DBCC CHECKIDENT ('DGEMPRES03..HCNDISHIS', RESEED, 67);
DBCC CHECKIDENT ('DGEMPRES03..HCNCAMTHC', RESEED, 3910);

delete DGEMPRES03..HCNTIPHIS where OID=68
delete DGEMPRES03..HCNDISHIS where HCNTIPHIS=68
delete DGEMPRES03..HCNCAMTHC where HCNTIPHIS=68
commit tran xxx