use DGEMPRES05
select * from DGEMPRES05..GENDETCON where GDEMODCONPAG is not NULL or GDECOBPLANBEN is not NULL
select * from DGEMPRES05..GENCONTRA where GECCONTRA is not NULL

begin tran xxx
update DGEMPRES01..GENCONTRA set GENCONTRA.GECCONTRA=pru.GECCONTRA
from DGEMPRES01..GENCONTRA pro inner join DGEMPRES05..GENCONTRA pru ON pro.oid=pru.OID
where pru.GECCONTRA is not NULL

update DGEMPRES01..GENDETCON set GENDETCON.GDEMODCONPAG=pru.GDEMODCONPAG, GENDETCON.GDECOBPLANBEN=pru.GDECOBPLANBEN
from DGEMPRES01..GENDETCON pro inner join DGEMPRES05..GENDETCON pru ON pro.oid=pru.OID
where pru.GDEMODCONPAG is not NULL or pru.GDECOBPLANBEN is not NULL
commit tran xxx
rollback tran xxx