use DGEMPRES21
select * from GENSERIPS where SIPCODIGO='877141'-----4316
select * from GENSERIPS where SIPCODIGO='877112'
select * from GENMANSER where GENSERIPS1=4316

--NOMBRE DEL 4678
--ARTERIOGRAFIA DE VASOS ABDOMINALES (SELECTIVAS)
--NOMBRE DEL ISS
--ARTERIOGRAFIA ABDOMINAL SELECTIVA DE ARTERIA GASTRODUODENAL. O TRONCO CELIACO. O MESENTERICA SUPERIOR O MESENTERICA INFERIOR

begin tran xx
update GENSERIPS set SIPCODIGO='877112' where SIPCODIGO='877141'
update GENMANSER set SMSCODSEE='877112', SMSNOMSEE='ARTERIOGRAFIA DE VASOS ABDOMINALES (SELECTIVAS)' where GENSERIPS1=4316
commit tran xxx

select * from GENSERIPS where SIPCODIGO='882295'-----4493
select * from GENSERIPS where SIPCODIGO='882292'
select * from GENMANSER where GENSERIPS1=4316

--NOMBRE DEL 4678
--ECOGRAFIA DOPPLER CON EVALUACION DE FLUJO SANGUINEO EN MASAS ABDOMINALES A COLOR
--NOMBRE DEL ISS
--DUPLEX SCANNING [DOPPLER- ECOGRAFIA] CON EVALUACION DE FLUJO SANGUINEO EN HIPERTENSION PORTAL

begin tran xx
update GENSERIPS set SIPCODIGO='882292' where SIPCODIGO='882295'
update GENMANSER set SMSCODSEE='882292', SMSNOMSEE='ECOGRAFIA DOPPLER CON EVALUACION DE FLUJO SANGUINEO EN MASAS ABDOMINALES A COLOR' where GENSERIPS1=4493
commit tran xxx

select * from GENSERIPS where SIPCODIGO='882312'-----4504
select * from GENSERIPS where SIPCODIGO='882314'
select * from GENMANSER where GENSERIPS1=4316

--NOMBRE DEL 4678
--ECOGRAFIA DOPPLER DE VASOS ARTERIALES DE MIEMBROS SUPERIORES A COLOR
--NOMBRE DEL ISS
--DUPLEX SCANNING [DOPPLER- ECOGRAFIA] DE VASOS ARTERIALES DE MIEMBROS SUPERIORES

begin tran xx
update GENSERIPS set SIPCODIGO='882314' where SIPCODIGO='882312'
update GENMANSER set SMSCODSEE='882314', SMSNOMSEE='ECOGRAFIA DOPPLER DE VASOS ARTERIALES DE MIEMBROS SUPERIORES A COLOR' where GENSERIPS1=4493
commit tran xxx

select top 5 * from GENSERIPS where SIPCODIGO='882333'-----4511
select top 5 * from GENSERIPS where SIPCODIGO='882335'
select * from GENMANSER where GENSERIPS1=4511

--NOMBRE DEL 4678
--ECOGRAFIA DOPPLER DE VASOS VENOSOS DE MIEMBROS INFERIORES A COLOR
--NOMBRE DEL ISS
--DUPLEX SCANNING [DOPPLER- ECOGRAFIA] DE VASOS VENOSOS DE MIEMBROS INFERIORES

begin tran xx
update GENSERIPS set SIPCODIGO='882335' where SIPCODIGO='882333'
update GENMANSER set SMSCODSEE='882335', SMSNOMSEE='ECOGRAFIA DOPPLER DE VASOS VENOSOS DE MIEMBROS INFERIORES A COLOR' where GENSERIPS1=4511
commit tran xxx

select top 5 * from GENSERIPS where SIPCODIGO='902201'-----3560
select top 5 * from GENSERIPS where SIPCODIGO='911009'
select top 5 * from GENMANSER where GENSERIPS1=3560

--NOMBRE DEL 4678
--COOMBS DIRECTO CUALITATIVO POR MICROTECNICA
--NOMBRE DEL ISS
--COOMBS DIRECTO. PRUEBA CUALITATIVA

begin tran xx
update GENSERIPS set SIPCODIGO='911009' where SIPCODIGO='902201'
update GENMANSER set SMSCODSEE='911009', SMSNOMSEE='COOMBS DIRECTO CUALITATIVO POR MICROTECNICA' where GENSERIPS1=3560
commit tran xxx


select top 5 * from GENSERIPS where SIPCODIGO='902202'-----3561
select top 5 * from GENSERIPS where SIPCODIGO='911003'
select top 5 * from GENMANSER where GENSERIPS1=3561

--NOMBRE DEL 4678
--ANTICUERPOS IRREGULARES DETECCION (CI RAI PAI EAI) POR MICROTECNIA
--NOMBRE DEL ISS
--COOMBS INDIRECTO. PRUEBA CUALITATIVA

begin tran xx
update GENSERIPS set SIPCODIGO='911003' where SIPCODIGO='902202'
update GENMANSER set SMSCODSEE='911003', SMSNOMSEE='ANTICUERPOS IRREGULARES DETECCION (CI RAI PAI EAI) POR MICROTECNIA' where GENSERIPS1=3561
commit tran xxx

select top 5 * from GENSERIPS where SIPCODIGO='902212'-----3729
select top 5 * from GENSERIPS where SIPCODIGO='911017'
select top 5 * from GENMANSER where GENSERIPS1=3729

--NOMBRE DEL 4678
--HEMOCLASIFICACION SISTEMAS ABO DIRECTA [HEMOCLASIFICACION GLOBULAR] POR MICROTECNICA
--NOMBRE DEL ISS
--HEMOCLASIFICACION GRUPO ABO Y FACTOR RH

begin tran xx
update GENSERIPS set SIPCODIGO='911017' where SIPCODIGO='902212'
update GENMANSER set SMSCODSEE='911017', SMSNOMSEE='HEMOCLASIFICACION SISTEMAS ABO DIRECTA [HEMOCLASIFICACION GLOBULAR] POR MICROTECNICA' where GENSERIPS1=3729
commit tran xxx

select top 5 * from GENSERIPS where SIPCODIGO='905411'-----4101
select top 5 * from GENSERIPS where SIPCODIGO='905410'
select top 5 * from GENMANSER where GENSERIPS1=4101

--NOMBRE DEL 4678
--VANCOMICINA AUTOMATIZADO
--NOMBRE DEL ISS
--VANCOMICINA. SEMICUANTITATIVA POR CROMATOGRAFIA DE CAPA FINA

begin tran xx
update GENSERIPS set SIPCODIGO='905410' where SIPCODIGO='905411'
update GENMANSER set SMSCODSEE='905410', SMSNOMSEE='VANCOMICINA AUTOMATIZADO' where GENSERIPS1=4101
commit tran xxx

select top 5 * from GENSERIPS where SIPCODIGO='906909'-----3584
select top 5 * from GENSERIPS where SIPCODIGO='966901'
select top 5 * from GENMANSER where GENSERIPS1=3584

--NOMBRE DEL 4678
--INFUSION DE ALIMENTACION ENTERAL POR SONDA
--NOMBRE DEL ISS
--CRIOGLOBULINAS

begin tran xx
update GENSERIPS set SIPCODIGO='966901' where SIPCODIGO='906909'
update GENMANSER set SMSCODSEE='966901', SMSNOMSEE='INFUSION DE ALIMENTACION ENTERAL POR SONDA' where GENSERIPS1=3584
commit tran xxx
