-------------------------------------------------------------------------------------------------------------
declare @FACTURA_INICIAL varchar(15) = '000000000000'
declare @FACTURA_FINAL   varchar(15) = 'P99999999999'
declare @ENTIDAD_INICIAL varchar(10)= '800251440'
declare @ENTIDAD_FINAL	 varchar(10)= '800251440'
declare @AUDITOR_INICIAL varchar(10)= 'BARAUJO'
declare @AUDITOR_FINAL   varchar(10)= 'BARAUJO'
declare @FECHA_RESPUESTA_INICIAL datetime = '2020-24-01 00:00:00'
declare @FECHA_RESPUESTA_FINAL	 datetime = '2021-30-08 23:59:59'
-------------------------------------------------------------------------------------------------------------
Select CXC.CXCDOCUME FACTURA,
  CXC.CXCDOCFECHA FECHA_FACTURA,
  Month(CXC.CXCDOCFECHA) MES_FACTURA,
  Year(CXC.CXCDOCFECHA) AÑO_FACTURA,
  CXC.CRNVALOR VALOR_FACTURA,
  TER.TERNUMDOC NIT,
  TER.TERNOMCOM ENTIDAD,
  DOC1.CDCONSEC Nº_GLOSA,
  CON.CCOCODIGO COD_GLOSA,
  CON.CCONOMBRE NOM_GLOSA,
  DOBJ.CROVALOBJ VALOR_GLOSA,
  DOBJ.CRDOBSERV OBSERVACION_GLOSA,
  (Select CT.CCOCODIGO From CRNCONOBJ CT, CRNTRAOBJD TD
  Where TD.CRNCONOBJ = CT.OID And TD.CRNRECOBJD = DOBJ.OID) CON_RESP,
  (Select CT.CCONOMBRE From CRNCONOBJ CT, CRNTRAOBJD TD
  Where TD.CRNCONOBJ = CT.OID And TD.CRNRECOBJD = DOBJ.OID) NOM_RESP,
  DOC2.CDCONSEC Nº_RESPUESTA,
  (Select Round((TD.CTDVALOBJ + ((TD.CTDVALOBJ * 2) / 98)), 0)
  From CRNTRAOBJD TD Where TD.CRNRECOBJD = DOBJ.OID) VALOR_ACEPTADO,
  (Select TD.CTDOBSERV From CRNTRAOBJD TD
  Where TD.CRNRECOBJD = DOBJ.OID) RESPUESTA,
  USU.USUNOMBRE COD_USUARIO_CONFIRMA,
  USU.USUDESCRI DESCRIPCION_USUARIO_CONFIRMA
From CRNCXC CXC Inner Join GENTERCER TER On CXC.GENTERCER = TER.OID
  Inner Join CRNRECOBJC COBJ On COBJ.CRNCXC = CXC.OID
  Inner Join CRNRECOBJD DOBJ On DOBJ.CRNRECOBJC = COBJ.OID
  Inner Join CRNDOCUME DOC1 On DOC1.OID = COBJ.OID
  Inner Join CRNCONOBJ CON On CON.OID = DOBJ.CRNCONOBJ
  Inner Join CRNTRAOBJC CTRA On CTRA.CRNRECOBJC = COBJ.OID
  Inner Join CRNDOCUME DOC2 On DOC2.OID = CTRA.OID
  Inner Join CRNTRAOBJD DTRA On DTRA.CRNRECOBJD = DOBJ.OID And DTRA.CRNTRAOBJC = CTRA.OID
  Inner Join GENUSUARIO USU On DOC2.GENUSUARIO2 = USU.OID
Where TER.TERNUMDOC >= @ENTIDAD_INICIAL And TER.TERNUMDOC <= @ENTIDAD_FINAL 
  And CXC.CXCDOCUME >= @FACTURA_INICIAL And CXC.CXCDOCUME <= @FACTURA_FINAL 
  And USU.USUNOMBRE >= @AUDITOR_INICIAL And USU.USUNOMBRE <= @AUDITOR_FINAL 
  And DOC2.CDFECCON >= @FECHA_RESPUESTA_INICIAL And DOC2.CDFECCON <= @FECHA_RESPUESTA_FINAL 
  And CTRA.CROESTADO In (1) And COBJ.CROESTADO = 1
-------------------------------------------------------------------------------------------------------------
--select top 5 * from GENTERCER where TERPRINOM like '%SANITAS%'
--select top 5 * from GENUSUARIO where USUNOMBRE like '%araujo%'
--select top 5 CXCDOCUME, * from CRNCXC
--select top 5 CDFECCON, * from CRNDOCUME
-------------------------------------------------------------------------------------------------------------