USE DGEMPRES21
select * from IFNINFOFIN---Concepto Informe Financiero
select * from IFNINFOFINC where ifccodigo='CORI111'
select * from IFNINFOFINR--Reporte
select * from IFNINFOFINCCT where IFNINFOFINC=60--Cuentas
select * from IFNINFOFINCF
select * from IFNINFOFINCL

select * from DGEMPRES01..IFNINFOFINC where ifccodigo='CORI111'
select * from DGEMPRES01..IFNINFOFINCCT where IFNINFOFINC=60--Cuentas
select * from DGEMPRES01..IFNCUENTA where oid in (select IFNCUENTA from DGEMPRES01..IFNINFOFINCCT where IFNINFOFINC=60)
select * from DGEMPRES01..IFNCUENTA where CUCCODIGO like '4%' and IFNNIVEL=10

DBCC CHECKIDENT ('DGEMPRES01..IFNINFOFINCCT', RESEED, 0);

begin tran xxx
delete DGEMPRES01..IFNINFOFINCCT
commit tran xxx

select * from DGEMPRES21..IFNINFOFINC where ifccodigo='CORI111'
select * from DGEMPRES21..IFNINFOFINCCT where IFNINFOFINC=60--Cuentas
select * from DGEMPRES21..IFNCUENTA where oid in (select IFNCUENTA from DGEMPRES01..IFNINFOFINCCT where IFNINFOFINC=60)
select * from DGEMPRES21..IFNCUENTA where CUCCODIGO like '4%' and IFNNIVEL=5
select * from DGEMPRES21..IFNINFOFINCCT order by OID desc


select * from DGEMPRES01..IFNINFOFINC-- where ifccodigo='CORI111'
select * from DGEMPRES21..IFNINFOFINC 

select * from DGEMPRES01..IFNINFOFINCL--2
select * from DGEMPRES21..IFNINFOFINCL--2
--update DGEMPRES01..IFNINFOFINCL set OID= where OID=

select IFNINFOFINCF, * from DGEMPRES01..IFNINFOFINC--3
select * from DGEMPRES21..IFNINFOFINC--3
select * from DGEMPRES21..IFNINFOFINC where IFNINFOFINCF=7
select IFNINFOFINCF, COUNT(*) from DGEMPRES21..IFNINFOFINC group by IFNINFOFINCF
update DGEMPRES01..IFNINFOFINC set OID= where OID=
update DGEMPRES01..IFNINFOFINC set IFNINFOFINCF=6 where IFNINFOFINCF=7

select * from DGEMPRES01..IFNINFOFINCF--4 
select * from DGEMPRES21..IFNINFOFINCF--4
update DGEMPRES01..IFNINFOFINCF set OID= where OID=

select * from DGEMPRES01..IFNINFOFINCCL--5
select * from DGEMPRES21..IFNINFOFINCCL--5
update DGEMPRES01..IFNINFOFINCCL set OID= where OID=
update DGEMPRES01..IFNINFOFINCCL set IFNINFOFINC=6 where IFNINFOFINC=7
update DGEMPRES01..IFNINFOFINCCL set IFNINFOFINCL=6 where IFNINFOFINCL=7

select * from DGEMPRES01..IFNINFOFINCCT--6--Cuentas
select * from DGEMPRES21..IFNINFOFINCCT--6--Cuentas

update DGEMPRES01..IFNINFOFINCCL set IFCCEXPRESION=REPLACE(REPLACE(REPLACE(REPLACE(IFCCEXPRESION, CHAR(09),''), CHAR(10),''), CHAR(11),''), CHAR(13),'')

select * from DGEMPRES01..IFNINFOFINR 
select * from DGEMPRES21..IFNINFOFINR
update DGEMPRES01..IFNINFOFINR set OID= where OID=
----------------------------------------------------------------------------------------------------------------
select * from DGEMPRES01..IFNINFOFINCCL 
select * from DGEMPRES21..IFNINFOFINCCL

select * from DGEMPRES01..IFNINFOFINCF
select * from DGEMPRES21..IFNINFOFINCF

select * from DGEMPRES01..IFNINFOFINR 
select * from DGEMPRES21..IFNINFOFINR

select * from DGEMPRES01..IFNINFOFINCCT---Cuentas
select * from DGEMPRES21..IFNINFOFINCCT

select * from DGEMPRES01..IFNINFOFINF--Sin Registros
select * from DGEMPRES21..IFNINFOFINF--Sin Registros

select * from DGEMPRES01..IFNINFOFINCLCT--Sin Registros
select * from DGEMPRES21..IFNINFOFINCLCT--Sin Registros

select * from DGEMPRES01..IFNINFOFINFP--Sin Registros
select * from DGEMPRES21..IFNINFOFINFP--Sin Registros

begin tran xxx
delete DGEMPRES01..IFNINFOFINCCT--2
--delete DGEMPRES01..IFNINFOFINCCL--1
--delete DGEMPRES01..IFNINFOFINC--3
--delete DGEMPRES01..IFNINFOFINR--4
--delete DGEMPRES01..IFNINFOFINCF--5
--delete DGEMPRES01..IFNINFOFINCL--6
--delete DGEMPRES01..IFNINFOFIN--7
--commit tran xxx
--rollback tran xxx

DBCC CHECKIDENT ('DGEMPRES01..IFNINFOFIN', RESEED, 1);
DBCC CHECKIDENT ('DGEMPRES01..IFNINFOFINCCT', RESEED, 0);

insert into DGEMPRES01..IFNINFOFIN select * from DGEMPRES21..IFNINFOFIN
insert into DGEMPRES01..IFNINFOFINCF select * from DGEMPRES21..IFNINFOFINCF
insert into DGEMPRES01..IFNINFOFINC select * from DGEMPRES21..IFNINFOFINC
insert into DGEMPRES01..IFNINFOFINCL select * from DGEMPRES21..IFNINFOFINCL
insert into DGEMPRES01..IFNINFOFINCCL select * from DGEMPRES21..IFNINFOFINCCL
insert into DGEMPRES01..IFNINFOFINCCT select * from DGEMPRES21..IFNINFOFINCCT
insert into DGEMPRES01..IFNINFOFINR select * from DGEMPRES21..IFNINFOFINR