use DGEMPRES01
SELECT REPLACE(REPLACE(IDENTIFICADOR,CHAR(10),''),CHAR(13),'') FROM

select top 5 * from INNPRODUC

update INNPRODUC set IPRDESCOR=rtrim(ltrim(IPRDESCOR))
update INNPRODUC set IPRDESLAR=rtrim(ltrim(IPRDESLAR))

select top 5 * from GENPACIEN 

select top 5 * from GENDETCON
select top 5 * from genmanser

begin tran xxx
--update genmanser set SMSNOMSEE=REPLACE(REPLACE(REPLACE(REPLACE(SMSNOMSEE, CHAR(09),''), CHAR(10),''), CHAR(11),''), CHAR(13),'')

--update GENPACIEN set PACPRINOM=REPLACE(REPLACE(REPLACE(REPLACE(PACPRINOM, CHAR(09),''), CHAR(10),''), CHAR(11),''), CHAR(13),'')
--update GENPACIEN set PACSEGNOM=REPLACE(REPLACE(REPLACE(REPLACE(PACSEGNOM, CHAR(09),''), CHAR(10),''), CHAR(11),''), CHAR(13),'')
--update GENPACIEN set PACPRIAPE=REPLACE(REPLACE(REPLACE(REPLACE(PACPRIAPE, CHAR(09),''), CHAR(10),''), CHAR(11),''), CHAR(13),'')
--update GENPACIEN set PACSEGAPE=REPLACE(REPLACE(REPLACE(REPLACE(PACSEGAPE, CHAR(09),''), CHAR(10),''), CHAR(11),''), CHAR(13),'')

--update GENPACIEN set PACPRINOM=REPLACE(PACPRINOM, ' ','')
--update GENPACIEN set PACSEGNOM=REPLACE(PACSEGNOM, ' ','')
--update GENPACIEN set PACPRIAPE=REPLACE(PACPRIAPE, ' ','')
--update GENPACIEN set PACSEGAPE=REPLACE(PACSEGAPE, ' ','')

--update GENDETCON set GDECODIGO=REPLACE(REPLACE(REPLACE(REPLACE(GDECODIGO,CHAR(9),''),CHAR(10),''),CHAR(11),''),CHAR(13),'')
--update GENDETCON set GDENOMBRE=REPLACE(REPLACE(REPLACE(REPLACE(GDENOMBRE,CHAR(9),''),CHAR(10),''),CHAR(11),''),CHAR(13),'')
--update GENSERIPS set SIPCODIGO=REPLACE(REPLACE(REPLACE(SIPCODIGO, CHAR(9),''), CHAR(10),''), CHAR(13),'')
--update GENSERIPS set SIPNOMBRE=REPLACE(REPLACE(REPLACE(SIPNOMBRE, CHAR(9),''), CHAR(10),''), CHAR(13),'')
--update GENSERIPS set SIPCODCUP=REPLACE(REPLACE(REPLACE(SIPCODCUP, CHAR(9),''), CHAR(10),''), CHAR(13),'')
--update GENSERIPS set SIPDESCUP=REPLACE(REPLACE(REPLACE(SIPDESCUP, CHAR(9),''), CHAR(10),''), CHAR(13),'')

update INNPRODUC set IPRDESCOR=REPLACE(REPLACE(IPRDESCOR,CHAR(09),''),CHAR(10),'')
update INNPRODUC set IPRDESLAR=REPLACE(REPLACE(IPRDESLAR,CHAR(09),''),CHAR(10),'')
update INNPRODUC set IPRDESCOR=REPLACE(REPLACE(IPRDESCOR,CHAR(11),''),CHAR(13),'')
update INNPRODUC set IPRDESLAR=REPLACE(REPLACE(IPRDESLAR,CHAR(11),''),CHAR(13),'')

update INNPRODUC set IPRDESCOR=rtrim(ltrim(IPRDESCOR))
update INNPRODUC set IPRDESLAR=rtrim(ltrim(IPRDESLAR))


update GENDIAGNO set DIANOMBRE=REPLACE(REPLACE(REPLACE(REPLACE(DIANOMBRE,CHAR(09),''),CHAR(10),''),CHAR(11),''),CHAR(13),'')
--update SLNSERPRO set SERDESSER=REPLACE(REPLACE(REPLACE(REPLACE(SERDESSER, CHAR(9),''),CHAR(10),''),CHAR(11),''),CHAR(13),'') where ADNINGRES1 = 2165383

--update DGEMPRES21..CRNNOTA set NOTOBSERVA=REPLACE(REPLACE(NOTOBSERVA,CHAR(10),''),CHAR(13),'') where NOTESTADO=0
commit tran xxx


update GENTERCERP set GPRNOMBRE=REPLACE(REPLACE(GPRNOMBRE,CHAR(09),''),CHAR(10),'')
update GENTERCERP set GPRNOMBRE=REPLACE(REPLACE(GPRNOMBRE,CHAR(09),''),CHAR(10),'')
update GENTERCERP set GPRNOMBRE=REPLACE(REPLACE(GPRNOMBRE,CHAR(11),''),CHAR(13),'')
update GENTERCERP set GPRNOMBRE=REPLACE(REPLACE(GPRNOMBRE,CHAR(11),''),CHAR(13),'')

update GENTERCERP set GPRNOMBRE=rtrim(ltrim(GPRNOMBRE))
update GENTERCERP set GPRNOMBRE=rtrim(ltrim(GPRNOMBRE))

select top 5 * from DGEMPRES01..INNGRUPO
select top 5 * from DGEMPRES01..INNSUBGRU
select top 5 * from DGEMPRES01..GENCONFAC
select top 5 * from DGEMPRES01..INNCCOMPR
select top 5 * from DGEMPRES01..INNMCOMPR
select top 5 * from DGEMPRES01..INNUNIDAD
select top 5 * from DGEMPRES01..GENTERCERP