------------------------------------------------------------------------------------------------------------------------------
declare @FECHA_INICIAL datetime ='2020-01-05 00:00:00'
declare @FECHA_FINAL    datetime ='2020-31-05 23:59:59'
------------------------------------------------------------------------------------------------------------------------------
SELECT 
	FAC.SFANUMFAC FACTURA
	,FAC.SFAFECFAC FECHA
	,RTrim(PAC.PACPRINOM)+' '+RTrim(PAC.PACSEGNOM)+' '+RTrim(PAC.PACPRIAPE)+' '+RTrim(PAC.PACSEGAPE) As NOMBRE
	,CASE pac.pactipdoc WHEN '1' THEN 'CC' WHEN '2' THEN 'CE'  	WHEN '3' THEN 'TI'  	WHEN '4' THEN 'RC' 
		WHEN '5' THEN 'PAS'  	WHEN '6' THEN 'ASI'  	WHEN '7' THEN 'MSI'  	WHEN '8' THEN 'NUIP' END AS TIPO
	,CASE pac.GPATIPPAC WHEN '0' THEN 'NINGUNO' WHEN '1' THEN 'CONTRIBUTIVO' WHEN '2' THEN 'SUBSIDIADO' WHEN '3' THEN 'VINCULADO' 
		WHEN '4' THEN 'PARTICULAR' WHEN '5' THEN 'OTRO' WHEN '6' THEN 'DESPLAZADO_Con' WHEN '7' THEN 'DESPLAZADO_Sub' 
		WHEN '8' THEN 'DESPLAZADO_No_Aseg' ELSE 'OTRO_' END AS TIP_Pac
	,PAC.PACNUMDOC As DOCUMENTO
	,ROUND((CONVERT (INT, GETDATE()) - CONVERT(INT, pac.gpafecnac)) / 365, 0) as EDAD
	,ING.AINFECING fecha_ingreso
	,EGR.ADEFECSAL fecha_egreso
	,DET.GDECODIGO COD_PLAN
	,DET.GDENOMBRE NOMBRE_PLAN
	,FAC.SFATOTFAC VR_ENTIDADL
	,FAC.SFAVALCAR - FAC.sfavarere CARTERA
	,FAC.SFAVALPAC VR_PACIENTE
	,FAC.SFAVALREC COPAGO
	,FAC.SFABARERE Base
	,FAC.sfavarere retencion
	,ING.AINCONSEC INGRESO
	,ING.AINNUMAUT AUTORIZACION
		,CASE ING.ainurgcon WHEN 0 THEN 'URGENCIAS' WHEN 1 THEN 'CONSULTA EXTERNA' WHEN 2 THEN 'NACIDO' WHEN 3 THEN 'REMITIDO' WHEN 4 THEN 'HOSPITALIZACION URGENCIAS' 
		WHEN 5 THEN 'HOSPITALIZACION' WHEN 6 THEN 'IMAGENES' WHEN 7 THEN 'LABORATORIO' ELSE 'OTRO' END AS Ingreso_Por
	,CASE ING.AINTIPING WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END AS Tipo_Ingreso
	,CASE ING.AINTIPRIE 
		WHEN 0 THEN 'NINGUNA'
		WHEN 1 THEN 'ACCIDENTE DE TRANSITO'
		WHEN 2 THEN 'CATASTROFE'
		WHEN 3 THEN 'ENFERMEDAD GENERAL Y MATERNIDAD'
		WHEN 4 THEN 'ACCIDENTE DE TRABAJO'
		WHEN 5 THEN 'ENFERMEDAD PROFESIONAL'
		WHEN 6 THEN 'ATENCIÓN INICIAL DE URGENCIAS'
		WHEN 7 THEN 'OTRO TIPO DE ACCIDENTE'
		WHEN 8 THEN 'LESIÓN POR AGRESIÓN'
		WHEN 9 THEN 'LESIÓN AUTOINFLIGIDA'
		WHEN 10 THEN 'MALTRATO FISICO'
		WHEN 11 THEN 'PROMOCIÓN Y PREVENCIÓN'
		WHEN 12 THEN 'OTRO'
		WHEN 13 THEN 'ACCIDENTE RABICO'
		WHEN 14 THEN 'ACCIDENTE OFIDICO'
		WHEN 15 THEN 'SOSPECHA DE ABUSO SEXUAL'
		WHEN 16 THEN 'SOSPECHA DE VIOLENCIA SEXUAL'
		WHEN 17 THEN 'SOSPECHA DE MALTRATO EMOCIONAL'
		END AS TIPO_RIESGO
	,REPLACE(REPLACE(REPLACE(REPLACE(RTRIM(USU.USUNOMBRE),CHAR(9),''),CHAR(10),''),CHAR(13),''),CHAR(99),'') AS  USUARIO
	,Case When FAC.SFADOCANU = 0 Then 'ACTIVA' When FAC.SFADOCANU = 1 Then 'ANULADO' End ESTADO 
	,CASE FAC.SFATIPDOC 
		WHEN 0 THEN 'Factura_Paciente'
		WHEN 1 THEN 'Factura_Entidad'
		WHEN 2 THEN 'Factura_CapitadaEstatal'
		WHEN 3 THEN 'Registro_ServiciosPrivada'
		WHEN 4 THEN 'Registro_FacturaGlobal'
		WHEN 5 THEN 'CuentaCobro_EntidadCapitada'
		WHEN 6 THEN 'Factura_EntidadCapitada'
		WHEN 7 THEN 'Factura_Global'
		WHEN 8 THEN 'CuentaCobro_PFGP'
		WHEN 9 THEN 'CuentaCobro_Vinculados'
		WHEN 10 THEN 'CuentaEntidades'
		WHEN 11 THEN 'CuentaCobro'
		WHEN 12 THEN 'Registro_CapitacionGlobal'
		WHEN 13 THEN 'CuentaCobro_Terceros'
		WHEN 14 THEN 'Devolucion_Particular'
		WHEN 15 THEN 'Factura_Radicada' END AS TIPO_FACTURA

FROM 
	SLNFACTUR FAC 
	INNER JOIN GENDETCON DET ON FAC.GENDETCON=DET.OID
	INNER JOIN ADNINGRESO ING ON FAC.ADNINGRESO=ING.OID
	INNER JOIN GENPACIEN  PAC ON ING.GENPACIEN=PAC.OID
	INNER JOIN GENUSUARIO USU ON FAC.GENUSUARIO1=USU.OID
	LEFT JOIN ADNEGRESO   EGR ON EGR.ADNINGRESO=ING.OID
WHERE 
	(FAC.SFAFECFAC >= @FECHA_INICIAL And FAC.SFAFECFAC <= @FECHA_FINAL)
------------------------------------------------------------------------------------------------------------------------------