IF OBJECT_ID('tempdb..#ordenes') IS NOT NULL
BEGIN
	DROP TABLE #ordenes
END 
	
-- tabla de ordenes de servicio
CREATE TABLE #ordenes (
	INNPROEPS INT
	,INNMANTAR INT
	,IMTFECINI DATETIME
	,IMTFECFIN DATETIME
	,IMTVALPRO MONEY
);


DECLARE @INNPROEPS INT;

DECLARE CRINNPROEPS CURSOR STATIC FOR
SELECT 
	INNPROEPS 
FROM 
	DGEMPRES01..INNMANTAR tar INNER JOIN DGEMPRES01..INNPROEPS eps ON tar.INNPROEPS=eps.OID
    WHERE eps.GENMANUAL=79 --and tar.INNPROEPS=30363 
GROUP BY 
	INNPROEPS 
HAVING COUNT(INNPROEPS) > 1

OPEN CRINNPROEPS
FETCH NEXT FROM CRINNPROEPS INTO @INNPROEPS

WHILE @@FETCH_STATUS = 0
BEGIN
		DECLARE @INNMANTAR INT, @IMTFECINI DATETIME, @IMTFECFIN DATETIME, @IMTVALPRO MONEY

		DECLARE CRINNMANTAR CURSOR STATIC FOR 
		SELECT OID AS INNMANTAR, IMTFECINI, IMTFECFIN, IMTVALPRO
		FROM 
			DGEMPRES01..INNMANTAR
		WHERE 
			INNPROEPS = @INNPROEPS 
		ORDER BY 
			IMTFECINI ASC 

		OPEN CRINNMANTAR
		FETCH NEXT FROM CRINNMANTAR INTO @INNMANTAR, @IMTFECINI, @IMTFECFIN, @IMTVALPRO
		IF @@CURSOR_ROWS > 1
			BEGIN
				WHILE @@FETCH_STATUS = 0
				BEGIN
				
					IF NOT EXISTS(SELECT INNMANTAR FROM #ordenes WHERE INNMANTAR = @INNMANTAR)
					BEGIN
						IF EXISTS (select OID from INNMANTAR where INNPROEPS=@INNPROEPS and OID>@INNMANTAR and ((IMTFECINI between @IMTFECINI and @IMTFECFIN) or (IMTFECFIN between @IMTFECINI and @IMTFECFIN)))
						BEGIN
							INSERT INTO #ordenes(INNPROEPS, INNMANTAR, IMTFECINI, IMTFECFIN, IMTVALPRO) VALUES(@INNPROEPS,@INNMANTAR, @IMTFECINI, @IMTFECFIN, @IMTVALPRO)
						END
					END 

					FETCH NEXT FROM CRINNMANTAR INTO @INNMANTAR, @IMTFECINI, @IMTFECFIN, @IMTVALPRO
				END
			END
		CLOSE CRINNMANTAR
		DEALLOCATE CRINNMANTAR
	
	FETCH NEXT FROM CRINNPROEPS INTO @INNPROEPS
END 

CLOSE CRINNPROEPS
DEALLOCATE CRINNPROEPS

SELECT 
	#ordenes.INNPROEPS
	,#ordenes.INNMANTAR
	,GENMANUAL.GENMANUAL
	,INNPRODUC.IPRCODIGO
	,INNPRODUC.IPRCUM
	,INNPRODUC.IPRDESCOR
	,#ordenes.IMTFECINI
	,#ordenes.IMTFECFIN
FROM 
	#ordenes 
	INNER JOIN DGEMPRES01..INNPROEPS ON INNPROEPS.OID = #ordenes.INNPROEPS
	INNER JOIN DGEMPRES01..INNPRODUC ON INNPRODUC.OID = INNPROEPS.INNPRODUC
	INNER JOIN DGEMPRES01..GENMANUAL ON GENMANUAL.OID = INNPROEPS.GENMANUAL
ORDER BY 
	INNPROEPS
	,IMTFECINI desc